### ISSUE TITLE
Error when adding a comment

### ISSUE THREAD

**Issue by zacharymarshal** [zacharymarshal/Differ#15]
I am not sure what he did to get the error but I am thinking maybe some character in the comment?

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "R"' in /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php:349 Stack trace: #0 /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php(349): PDOStatement->execute(Array) #1 /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php(1501): ORM::_execute('SELECT \* FROM "...', Array, 'default') #2 /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php(511): ORM->_run() #3 /home/tbasilio/public_html/Differ/vendor/j4mie/paris/paris.php(118): ORM->find_one('R') #4 /home/tbasilio/public_html/Differ/lib/Differ/CommentSaver.php(26): ORMWrapper->find_one('R') #5 /home/tbasilio/public_html/Differ/public/index.php(88): Differ\CommentSaver->save() #6 [internal function]: {closure}('1008') #7 /home/tbasilio/public_html/Differ/lib/limonade.php(429): call_user_func_array(Object(Closure), Array) #8 /home/tbasilio/public_html/Differ/public/index.php(118 in /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php on line 349

**Comment by tbasilio** [comment]
I typed in something like "Please rename this to Foo/Bar/Baz.php"

On Wed, Oct 30, 2013 at 4:29 PM, Zachary Rankin notifications@github.comwrote:

> I am not sure what he did to get the error but I am thinking maybe some
> character in the comment?
> 
> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "R"' in /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php:349 Stack trace: #0 /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php(349): PDOStatement->execute(Array) #1 /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php(1501): ORM::_execute('SELECT \* FROM "...', Array, 'default') #2 /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php(511): ORM->_run() #3 /home/tbasilio/public_html/Differ/vendor/j4mie/paris/paris.php(118): ORM->find_one('R') #4 /home/tbasilio/public_html/Differ/lib/Differ/CommentSaver.php(26): ORMWrapper->find_one('R') #5 /home/tbasilio/public_html/Differ/public/index.php(88): Differ\CommentSaver->save() #6 [internal function]: {closure}('1008') #7 /home/tbasilio/public_html/Differ/lib/limonade.php(429): call_user_func_array(Object(Closure),
>  Array) #8 /home/tbasilio/public_html/Differ/public/index.php(118 in /home/tbasilio/public_html/Differ/vendor/j4mie/idiorm/idiorm.php on line 349
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zacharyrankin/Differ/issues/15
> .

## 

Taylor Basilio / tbasilio@codingavenue.com
Coding Avenue / http://codingavenue.com
+1 (951) 808 - 5597
